version: "3"

services:
  server:
   build: .
   volumes:
    - .:/app
   ports:
    - 9143:9143

  influxDB:
   image: influxdb:1.3
   entrypoint: bash
   command: influxdb/boot-up.sh
   volumes:
    - ./influxdb/:/influxdb
  
  grafana:
   image: grafana/grafana
   ports:
     - 3000:3000